### ISSUE TITLE
Github link from SVN.

### ISSUE THREAD

**Issue by stoecker** [JOSM/kartverketimport#1]
You caused major trouble with your external link in OSM SVN and I reverted it.

Beside the errors you made, only projects in the group
https://github.com/JOSM
are allowed there. I.e. projects, where we have write access. If you agree to make this the main data source, then a link is fine. If not, then you can't participate in the automatic translation stuff and only add the link to your final JAR file here:

https://josm.openstreetmap.de/wiki/PluginsSource

Which is required in any case BTW.

**Comment by tibnor** [comment]
@stoecker  I'm so sorry! I would like to have the project in the JOSM-group. Can you add/fork the project to the group?
I have also added a link to the wiki.

**Comment by don-vip** [comment]
Hi tibnor,
see https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization
I have created a new team and invited you in it, you must accept the invitation, then proceed to the transfer.
After that it will be ok to re-add the SVN external link.

**Comment by stoecker** [comment]
> After that it will be ok to re-add the SVN external link.

But please add it in "plugins" and don't again kill our core link. :-)
